### ISSUE TITLE
List of high-level requirements

### ISSUE THREAD

**Issue by onatbas** [SWE574-Unity/Heritage#8]
I guess, up until next week's class we should start by gathering some high-level requirements or at least what we understand from the project description and then discuss them with the instructor, check whether our understanding is correct or not. 

Here's what I propose:
1. Let's add our user story candidates as we understand them here.
2. Discuss them throughly by citing with document.
3. Come up with a list of user stories and confirm with instructor.

After this process, we can start actually designing the application we're developing, because we're gonna have some stuff to discuss and design on.

What do you think @SWE574-TeamUnity/unity ?

---

Here's the link to document: https://piazza.com/boun.edu.tr/spring2017/swe574/resources
Here are the figures in raw form: [Figure 1](https://cloud.githubusercontent.com/assets/714795/22973015/b5d8c58a-f395-11e6-9db9-7175901ce61e.png), [Figure 2](https://cloud.githubusercontent.com/assets/714795/22973017/b809f11c-f395-11e6-935f-af7360d1a4a3.png), [Figure 3](https://cloud.githubusercontent.com/assets/714795/22973018/b9732ad2-f395-11e6-85a0-9aa57b7dc8c6.png)

**Comment by bozavci** [comment]
There are the requirements are gather from the document and questions I had in mind. There are not much detail in the document I think the idea is that we should elicitate detailed requirements via interviews.

## Content Generators (People who creating annotations)

### 	HL Requirements
- Users will be able to login to the system
- Users will be able to register to the system.
- Users will be able to generate annotations
- Users will be able to upload media with generated annotations
- Annotations will be created via a Modzilla Firefox plugin
- W3C Web Annotation Data Model will be used as data model for annotations
- JSON-LD will be used to validate annotations.
- Annotations will be stored in the system.

### 	Questions
- Are the users required to login to create annotations ? 
- Are there spesific subjects that will available for annotations ?
- Are "Content Consumer" account will be usable for "Content Generator" account ?
- What are the limitations on uploaded media (Storage, File type etc) ? 

## Content Consumers (People who are searching and viewing content)

### HL Requirements
- Users will be able to login to the system.
- Users will be able to register to the system.
- Users will be able to search previously created annotations.
- Users will be able to view recommended annotations.

### Questions 
- Are users required to login in order to use the system ?
- What is the difference between search and detailed search ?
- Are we expected to perform a text search ? If so are there any non-functional requirements for text-search (Size , Query Time etc)

**Comment by edipcilli** [comment]
### Questions
1) What kind of API's will be used?   
2) Should we think about NF requirements like security , etc. ?

**Comment by eylulakar** [comment]
In addition to above items I'd like to add the following ones:

**Requirement:**

- Users will be able to edit annotations. (Annotaton history must be stored and viewable.)

**Questions**

- Is it expected from us to have any specific differences in web and mobile applications(except location based activities)? Or are we allowed to develop them as we'd like, as long as the functionalities in both meet the requirements?

- What are public users able to do in the system? (for example, only searching and viewing content ability?)

**Comment by onatbas** [comment]
Here's another proposal. I'm trying to address different kinds of information to be linked with the annotations.

One of the things requested in the class is to have the ability to add different kinds of information to the annotation. Like, 'Dates' or 'Historic Information', or 'Cultural Origin' stuff like that. It seems Wikipedia has solved this kind of feature. When you visit a random page, the panel you see at the right shows different information for any kind of resource. I think this is crucial for addressing that as well. 

Let me give more brief explanation with an example, I'm using Queen Anne's Revenge ship. Being a ship, It should have histroic infrmation, previous owners and active geographic locations. Here's whatthe page looks like:

![screen shot 2017-02-20 at 15 16 23](https://cloud.githubusercontent.com/assets/714795/23124752/952d7b08-f77f-11e6-8349-eeb8a9364179.png)


You see, there's a markup for every used information box called 'Infobox' and users can add, remove any kind of information like that and link with the information the same functionality is one way or another is going to be implemented in our system as well. So here's my requirement proposals:


1. Content creators should be able to have Infoboxes linked to their annotations. 
2. Content creators should be able to see possible Infobox types when creating their annotations. 
3. Content creators should be able to add/propose new infobox types to the system.

The wording is always flexible, but I think I made the point on the general idea. 

Thoughts?

**Comment by onatbas** [comment]
@bozavci 
I like your list. There's this distinction with annotations, though: 

Annotations require the content to exist in the web. 

So we may re-write your requirement to something like this, maybe? : 

1. Users will be able to generate annotations to pre-existent web sources.

This brings up this question: What happens if no content has been found in the web? Here's my recommendation: 

2. Users will be able to generate sources to be annotated if a relevant web source could not be found. 
(We probably are gonna need to add a blog feature to let our users post a content, first.)

If we have this, we might add this as well:
3.  Users will be able to use a pre-existent source to merge their annotation targets with.
4. Users will be prompted with relevant pre-existent anotation sources. 
(Like, when a user wants to annotate queen anne's revenge using a random page, but it has been annotated before with a better target.)

**Comment by onatbas** [comment]
Some mobile proposals:

1. Users will be able to take a picture from an android mobile device and upload it as content.
2. Users will be able to make annotations with the photos they took, targeting a different content.
3. Users will be able to make annotations on the photo they took. (In this case, the photo is the content being annotated, this addresses the case when no content is found on web.)

**Comment by onatbas** [comment]
Proposals to specifically define the supported media types :

1. Users will be able to annotate a whole web page.
2. Users will be able to annotate specific portion of a text from a web source. 
3. Users will be able to annotate a specific photo or a portion of that photo.
4. Users will be able to browse through annotations.
5. Users will be able to access the annotated target from the list of annotations (provided by the search functionality.)

**Comment by atabn** [comment]
Some additional notes:

What types of users should be there? What rights do different user types have? Last week we discussed in class about moderated/fully crowdsourced approaches, but it's not clear if we are free to use either approach.
We have aggreed on AWS as hosting service, but I think we should confirm it with the customer.

**Comment by onatbas** [comment]
@atabn Great point I think this decision on how to moderate the content deserves it's own Issue. Could you open a case for it? Let's add a point about that.

**Comment by eylulakar** [comment]
Closing this. While reporting the finalized requirements documentation this issue can be considered again.
